name: Workflow lors d'un push
on: push
jobs:
  mon_job:
    name: Build teste et run mon app
    runs-on: ubuntu-latest
    steps:
      - name: Récup le code
        uses: actions/checkout@v4
      - name: cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: devops-node-module-${{ hashFiles('**/package-lock.json') }}
      - name: Install node_modules
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Start
        run: npm run start
      - name: Sommaire
        run: |
          echo "# Résumé du step" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "On peut ajouter du markdown dans le fichier d'environnement GITHUB_STEP_SUMMARY. Il s'affichera sur la page de résumé d'une exécution de workflow." >> $GITHUB_STEP_SUMMARY
          echo "On pourrait par exemple y afficher les résultats de nos tests." >> $GITHUB_STEP_SUMMARY

  mon_2e_job:
    name: Affiche si le test a réussi ou échoué
    runs-on: ubuntu-latest
    needs: mon_job
    steps:
      - name: Vérifier le statut des tests
      run: |
        if npm run test; then
          echo "Les tests ont réussi"
          exit 0
        else
          echo "Les tests ont échoué"
          exit 1
        fi